-- 코드를 입력하세요
# SELECT I.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
# FROM MEMBER_PROFILE I
# JOIN REST_REVIEW R
# ON I.MEMBER_ID = R.MEMBER_ID
# GROUP BY I.MEMBER_ID
# H

# SELECT *
# FROM MEMBER_PROFILE


# SELECT I.MEMBER_ID
# FROM MEMBER_PROFILE I
# JOIN REST_REVIEW R
# ON I.MEMBER_ID = R.MEMBER_ID
# GROUP BY I.MEMBER_ID
# ORDER BY COUNT(I.MEMBER_ID) DESC
# LIMIT 1

SELECT I.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE I
JOIN REST_REVIEW R
ON I.MEMBER_ID = R.MEMBER_ID
WHERE I.MEMBER_ID = (
    SELECT I.MEMBER_ID
    FROM MEMBER_PROFILE I
    JOIN REST_REVIEW R
    ON I.MEMBER_ID = R.MEMBER_ID
    GROUP BY I.MEMBER_ID
    ORDER BY COUNT(I.MEMBER_ID) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT